# -*- coding: utf-8 -*-
"""App_File.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1txK1z_cQVCgOE6QfJzgufM1yTMvZzklj
"""

from flask import Flask, request
import numpy as np
import pickle
import pandas as pd
import flasgger
from flasgger import Swagger

app=Flask(__name__)
run_with_ngrok(app)
Swagger(app)

pickle_in = open("classifier1.pkl","rb")
classifier1=pickle.load(pickle_in)

pickle_in = open("classifier2.pkl","rb")
classifier2=pickle.load(pickle_in)

pickle_in = open("classifier3.pkl","rb")
classifier3=pickle.load(pickle_in)

pickle_in = open("classifier4.pkl","rb")
classifier4=pickle.load(pickle_in)

@app.route('/')
def welcome():
    return "Welcome All!! This is the Employee Performance Improvement Using Analytics Page - Designed and Built End to End by AI RANGERS"

@app.route('/Employee Rating Prediction Using Random Forest.Enter the Values Manually',methods=["Get"])
def predict_performance_RFM():
    
    """Click here for Employee’s Performance Analysis and Prediction using Random Forest.
    <b> ACCURACY LEVEL OF RANDOM FOREST : PRECISION - 96% || RECALL - 96% || F1-SCORE - 96%</b>
    
    
    <b>Ten Parameters to be Entered are:
    
    
    01. Employee Last Salary Hike Percentage : Last Hike received by an Employee in percentage
    
    02. Employee Environment Satisfaction : Employee's Work Life Balance Satisfaction Annual Rating
    
    03. Years Since The Last Promotion : Employee's no. of Years since Last Promotion
    
    04. Employee Department : Employee's current Department - Sales OR Human Resources OR Development OR Data Science OR Research & Development OR Finance
    
    05. Years of Experience In Current Role : Employee's no. of Years in the Existing Role
    
    06. Employee Job Role : Includes - Sales Executive,Manager,Developer,Sales Representative,Senior Developer R&D,Data Scientist,Finance Manager,Business Analyst,Technical Lead,Research Director,Delivery Manager
    
    07. Years With Current Manager: Number of years spent with the Existing Manager
    
    08. Distance From Home: How far does the Employee Stay ?
    
    09. Years of Experience At Existing Company: Experience in years spent in the Existing Company
    
    10. Number of Companies Worked: How many Companies has the employee worked at.</b>
    ---
    parameters:  
      - name: Employee Last Salary Hike Percent
        in: query
        type: integer
        minimum: 0
        maximum: 25
        default: 0
        required: true
        description: <b>Value Ranges from 1% to 25%</b>.
      - name: Employee Environment Satisfaction
        in: query
        type: integer
        minimum: 1
        maximum: 4
        default: 0
        required: true
        description: <b>Values Ranges from 1 to 4. Enter 1 = LOW; 2 = MEDIUM; 3 = HIGH; 4 = VERY HIGH</b>. 
      - name: Years Since The Last Promotion
        in: query
        type: integer
        minimum: 1
        maximum: 15
        default: 0
        required: true
        description: <b>Values Ranges from 1 to 15 years. Enter any value between 1 & 15</b>.
      - name: Employee Department
        in: query
        type: integer
        minimum: 1
        maximum: 6
        default: 0
        required: true
        description: <b>Values Ranges from 1 to 6. Enter 1 = SALES; 2 = HUMAN RESOURCES; 3 = DEVELOPMENT; 4 = DATA SCIENCE; 5 = RESEARCH & DEVELOPMENT; 6 = FINANCE</b>.
      - name: Years of Experience In Current Role
        in: query
        type: integer
        minimum: 1
        maximum: 20
        default: 2
        required: true
        description: <b>Values Ranges from 1 to 20 years. Enter any value between 1 & 20</b>.
      - name: Employee Job Role
        in: query
        type: integer
        minimum: 1
        maximum: 10
        default: 2
        required: true
        description: <b>Values between 1 to 10. Enter 1 = Sales Executive; 2 = Manager; 3 = Developer; 4 = Sales Representative; 5 = Senior Developer R&D; 6 = Data Scientist; 7 = Finance Manager; 8 = Business Analyst; 9 = Technical Lead; 10 = Research Director; 11 = Delivery Manager</b>.
      - name: Years With Current Manager
        in: query
        type: integer
        minimum: 1
        maximum: 18
        default: 1
        required: true
        description: <b>Values Ranges from 1 to 18 years. Enter any value between 1 & 18</b>.
      - name: Distance From Home
        in: query
        type: integer
        minimum: 1
        maximum: 30
        default: 1
        required: true
        description: <b>Values Ranges from 1 to 30 Kilometers. Enter any value between 1 & 30</b>.
      - name: Years of Experience At Existing Company
        in: query
        type: integer
        minimum: 0
        maximum: 40
        default: 1
        required: true
        description: <b>Values Ranges from 1 to 40 years. Enter any value between 1 & 40</b>.
      - name: Number of Companies Worked
        in: query
        type: integer
        minimum: 1
        maximum: 10
        default: 1
        required: true
        description: <b>Values Ranges from 1 to 10 companies. Enter any value between 1 & 10</b>.
    responses:
        200:
            description: The AI RANGERS, Human resources department currently conducts performance appraisals with a 4-level rating scale focused on whether or not employees meet company goals.<b>Overall performance ratings are given on a 4-point scale, observing employees with performances that are Excellent (4), Good  (3), Needs Improvement (2), and Unacceptable (1)</b>.
        
    """
    EmpLastSalaryHikePercent=request.args.get("Employee Last Salary Hike Percent")
    EmpEnvironmentSatisfaction=request.args.get("Employee Environment Satisfaction")
    YearsSinceLastPromotion=request.args.get("Years Since The Last Promotion")
    EmpDepartment=request.args.get("Employee Department")
    ExperienceYearsInCurrentRole=request.args.get("Years of Experience In Current Role")
    EmpJobRole=request.args.get("Employee Job Role")
    YearsWithCurrManager=request.args.get("Years With Current Manager")
    DistanceFromHome=request.args.get("Distance From Home")
    ExperienceYearsAtThisCompany=request.args.get("Years of Experience At Existing Company")
    NumCompaniesWorked=request.args.get("Number of Companies Worked")
      
    prediction=classifier1.predict([[EmpLastSalaryHikePercent,EmpEnvironmentSatisfaction,YearsSinceLastPromotion,EmpDepartment,ExperienceYearsInCurrentRole,EmpJobRole,YearsWithCurrManager,DistanceFromHome,ExperienceYearsAtThisCompany,NumCompaniesWorked]])
    print(prediction)
    return "The RANDOM FOREST CLASSIFIER says the Employee performance Ratings falls into class "+str(prediction)


@app.route('/Employee Rating Prediction Using Decision Tree. Enter the Values Manually',methods=["Get"])
def predict_performance_DTM():
    
    """Click here for Employee’s Performance Analysis and Prediction using Decision Tree.
    <b>ACCURACY LEVEL OF Decision Tree : PRECISION - 90% || RECALL - 90% || F1-SCORE - 90%</b>
    
    
    <b>Ten Parameters to be Entered are:
    
    
    01. Employee Last Salary Hike Percentage : Last Hike received by an Employee in percentage
    
    02. Employee Environment Satisfaction : Employee's Work Life Balance Satisfaction Annual Rating
    
    03. Years Since The Last Promotion : Employee's no. of Years since Last Promotion
    
    04. Employee Department : Employee's current Department - Sales OR Human Resources OR Development OR Data Science OR Research & Development OR Finance
    
    05. Years of Experience In Current Role : Employee's no. of Years in the Existing Role
    
    06. Employee Job Role : Includes - Sales Executive,Manager,Developer,Sales Representative,Senior Developer R&D,Data Scientist,Finance Manager,Business Analyst,Technical Lead,Research Director,Delivery Manager
    
    07. Years With Current Manager: Number of years spent with the Existing Manager
    
    08. Distance From Home: How far does the Employee Stay ?
    
    09. Years of Experience At Existing Company: Experience in years spent in the Existing Company
    
    10. Number of Companies Worked: How many Companies has the employee worked at.</b>
    ---
    parameters:  
      - name: Employee Last Salary Hike Percent
        in: query
        type: integer
        minimum: 0
        maximum: 25
        default: 1
        required: true
        description: <b>Value Ranges from 1% to 25%</b>. 
      - name: Employee Environment Satisfaction
        in: query
        type: integer
        minimum: 1
        maximum: 4
        default: 2
        required: true
        description: <b>Values Ranges from 1 to 4. Enter 1 = LOW; 2 = MEDIUM; 3 = HIGH; 4 = VERY HIGH</b>. 
      - name: Years Since The Last Promotion
        in: query
        type: integer
        minimum: 1
        maximum: 15
        default: 1
        required: true
        description: <b>Values Ranges from 1 to 15 years. Enter any value between 1 & 15</b>.content
      - name: Employee Department
        in: query
        type: integer
        minimum: 1
        maximum: 6
        default: 1
        required: true
        description: <b>Values Ranges from 1 to 6. Enter 1 = SALES; 2 = HUMAN RESOURCES; 3 = DEVELOPMENT; 4 = DATA SCIENCE; 5 = RESEARCH & DEVELOPMENT; 6 = FINANCE</b>. content
      - name: Years of Experience In Current Role
        in: query
        type: integer
        minimum: 1
        maximum: 20
        default: 2
        required: true
        description: <b>Values Ranges from 1 to 20 years. Enter any value between 1 & 20</b>.content
      - name: Employee Job Role
        in: query
        type: integer
        minimum: 1
        maximum: 10
        default: 2
        required: true
        description: <b>Values between 1 to 10. Enter 1 = Sales Executive; 2 = Manager; 3 = Developer; 4 = Sales Representative; 5 = Senior Developer R&D; 6 = Data Scientist; 7 = Finance Manager; 8 = Business Analyst; 9 = Technical Lead; 10 = Research Director; 11 = Delivery Manager</b>.
      - name: Years With Current Manager
        in: query
        type: integer
        minimum: 1
        maximum: 18
        default: 1
        required: true
        description: <b>Values Ranges from 1 to 18 years. Enter any value between 1 & 18</b>.
      - name: Distance From Home
        in: query
        type: integer
        minimum: 1
        maximum: 30
        default: 1
        required: true
        description: <b>Values Ranges from 1 to 30 Kilometers. Enter any value between 1 & 30</b>.
      - name: Years of Experience At Existing Company
        in: query
        type: integer
        minimum: 0
        maximum: 40
        default: 1
        required: true
        description: <b>Values Ranges from 1 to 40 years. Enter any value between 1 & 40</b>.
      - name: Number of Companies Worked
        in: query
        type: integer
        minimum: 1
        maximum: 10
        default: 1
        required: true
        description: <b>Values Ranges from 1 to 10 companies. Enter any value between 1 & 10</b>.
    responses:
        200:
            description: The ABC, Berkeley human resources department currently conducts performance appraisals with a 4-level rating scale focused on whether or not employees meet company goals.<b>Overall performance ratings are given on a 4-point scale, observing employees with performances that are Excellent (4), Good  (3), Needs Improvement (2), and Unacceptable (1)</b>.
        
    """
    EmpLastSalaryHikePercent=request.args.get("Employee Last Salary Hike Percent")
    EmpEnvironmentSatisfaction=request.args.get("Employee Environment Satisfaction")
    YearsSinceLastPromotion=request.args.get("Years Since The Last Promotion")
    EmpDepartment=request.args.get("Employee Department")
    ExperienceYearsInCurrentRole=request.args.get("Years of Experience In Current Role")
    EmpJobRole=request.args.get("Employee Job Role")
    YearsWithCurrManager=request.args.get("Years With Current Manager")
    DistanceFromHome=request.args.get("Distance From Home")
    ExperienceYearsAtThisCompany=request.args.get("Years of Experience At Existing Company")
    NumCompaniesWorked=request.args.get("Number of Companies Worked")
      
    prediction2=classifier2.predict([[EmpLastSalaryHikePercent,EmpEnvironmentSatisfaction,YearsSinceLastPromotion,EmpDepartment,ExperienceYearsInCurrentRole,EmpJobRole,YearsWithCurrManager,DistanceFromHome,ExperienceYearsAtThisCompany,NumCompaniesWorked]])
    print(prediction2)
    return "The DECISION TREE CLASSIFIER says the Employee performance Ratings falls into class"+str(prediction2)




@app.route('/Employee Rating Prediction Using Random Forest- File Upload',methods=["POST"])
def predict_performance_RFFU():
    """Click Here to Upload File & Predict Performance Rating of Employee Using Random Forest 
    
    <b> ACCURACY LEVEL OF RANDOM FOREST : PRECISION - 96% || RECALL - 96% || F1-SCORE - 96%</b>
    
    Please try uploading an Excel file with multiple Inputs for Prediction here. The Model predicts the output of the form of an array.
    
    <b>Ten Parameters to be Entered are:
    
    
    01. Employee Last Salary Hike Percentage : Last Hike received by an Employee in percentage
    
    02. Employee Environment Satisfaction : Employee's Work Life Balance Satisfaction Annual Rating
    
    03. Years Since The Last Promotion : Employee's no. of Years since Last Promotion
    
    04. Employee Department : Employee's current Department - Sales OR Human Resources OR Development OR Data Science OR Research & Development OR Finance
    
    05. Years of Experience In Current Role : Employee's no. of Years in the Existing Role
    
    06. Employee Job Role : Includes - Sales Executive,Manager,Developer,Sales Representative,Senior Developer R&D,Data Scientist,Finance Manager,Business Analyst,Technical Lead,Research Director,Delivery Manager
    
    07. Years With Current Manager: Number of years spent with the Existing Manager
    
    08. Distance From Home: How far does the Employee Stay ?
    
    09. Years of Experience At Existing Company: Experience in years spent in the Existing Company
    
    10. Number of Companies Worked: How many Companies has the employee worked at.</b>

    ---
    parameters:
      - name: file
        in: formData
        type: file
        required: true
      
    responses:
        200:
            description: The ABC, Berkeley human resources department currently conducts performance appraisals with a 4-level rating scale focused on whether or not employees meet company goals.<b>Overall performance ratings are given on a 4-point scale, observing employees with performances that are Excellent (4), Good  (3), Needs Improvement (2), and Unacceptable (1)</b>.
        
        
    """
    df_test=pd.read_excel(request.files.get("file"))
    print(df_test.head())
    prediction3=classifier1.predict(df_test)
    
    return str(list(prediction3))



@app.route('/Employee Rating Prediction Using Decision Tree- File Upload',methods=["POST"])
def predict_performance_DTFU():
    """Click Here to Predict Performance Rating of Employee Using Decision Tree
    <b>Ten Parameters to be Entered are:
    
    
    01. Employee Last Salary Hike Percentage : Last Hike received by an Employee in percentage
    
    02. Employee Environment Satisfaction : Employee's Work Life Balance Satisfaction Annual Rating
    
    03. Years Since The Last Promotion : Employee's no. of Years since Last Promotion
    
    04. Employee Department : Employee's current Department - Sales OR Human Resources OR Development OR Data Science OR Research & Development OR Finance
    
    05. Years of Experience In Current Role : Employee's no. of Years in the Existing Role
    
    06. Employee Job Role : Includes - Sales Executive,Manager,Developer,Sales Representative,Senior Developer R&D,Data Scientist,Finance Manager,Business Analyst,Technical Lead,Research Director,Delivery Manager
    
    07. Years With Current Manager: Number of years spent with the Existing Manager
    
    08. Distance From Home: How far does the Employee Stay ?
    
    09. Years of Experience At Existing Company: Experience in years spent in the Existing Company
    
    10. Number of Companies Worked: How many Companies has the employee worked at.</b>

    ---
    parameters:
      - name: file
        in: formData
        type: file
        required: true
      
    responses:
        200:
            description: The ABC, Berkeley human resources department currently conducts performance appraisals with a 4-level rating scale focused on whether or not employees meet company goals.<b>Overall performance ratings are given on a 4-point scale, observing employees with performances that are Excellent (4), Good  (3), Needs Improvement (2), and Unacceptable (1)</b>.
        
        
    """
    df_test=pd.read_excel(request.files.get("file"))
    print(df_test.head())
    prediction4=classifier2.predict(df_test)
    
    return str(list(prediction4))



@app.route('/Employee Rating Prediction Using XGBoost- File Upload',methods=["POST"])
def predict_performance_XGBoostFU():
    """Click Here to Upload File & Predict Performance Rating of Employee Using Random Forest 
    
    <b> ACCURACY LEVEL OF RANDOM FOREST : PRECISION - 95% || RECALL - 95% || F1-SCORE - 95%</b>
    
    Please try uploading an Excel file with multiple Inputs for Prediction here. The Model predicts the output of the form of an array.
    
    <b>Ten Parameters to be Entered are:
    
    
    01. Employee Last Salary Hike Percentage : Last Hike received by an Employee in percentage
    
    02. Employee Environment Satisfaction : Employee's Work Life Balance Satisfaction Annual Rating
    
    03. Years Since The Last Promotion : Employee's no. of Years since Last Promotion
    
    04. Employee Department : Employee's current Department - Sales OR Human Resources OR Development OR Data Science OR Research & Development OR Finance
    
    05. Years of Experience In Current Role : Employee's no. of Years in the Existing Role
    
    06. Employee Job Role : Includes - Sales Executive,Manager,Developer,Sales Representative,Senior Developer R&D,Data Scientist,Finance Manager,Business Analyst,Technical Lead,Research Director,Delivery Manager
    
    07. Years With Current Manager: Number of years spent with the Existing Manager
    
    08. Distance From Home: How far does the Employee Stay ?
    
    09. Years of Experience At Existing Company: Experience in years spent in the Existing Company
    
    10. Number of Companies Worked: How many Companies has the employee worked at.</b>

    ---
    parameters:
      - name: file
        in: formData
        type: file
        required: true
      
    responses:
        200:
            description: The ABC, Berkeley human resources department currently conducts performance appraisals with a 4-level rating scale focused on whether or not employees meet company goals.<b>Overall performance ratings are given on a 4-point scale, observing employees with performances that are Excellent (4), Good  (3), Needs Improvement (2), and Unacceptable (1)</b>.
        
        
    """
    df_test=pd.read_excel(request.files.get("file"))
    print(df_test.head())
    prediction5=classifier3.predict(df_test)
    
    return str(list(prediction5))



@app.route('/Employee Rating Prediction Using Light GBM- File Upload',methods=["POST"])
def predict_performance_LGBMFU():
    """Click Here to Upload File & Predict Performance Rating of Employee Using Random Forest 
    
    <b> ACCURACY LEVEL OF RANDOM FOREST : PRECISION - 95% || RECALL - 95% || F1-SCORE - 95%</b>
    
    Please try uploading an Excel file with multiple Inputs for Prediction here. The Model predicts the output of the form of an array.
    
    <b>Ten Parameters to be Entered are:
    
    
    01. Employee Last Salary Hike Percentage : Last Hike received by an Employee in percentage
    
    02. Employee Environment Satisfaction : Employee's Work Life Balance Satisfaction Annual Rating
    
    03. Years Since The Last Promotion : Employee's no. of Years since Last Promotion
    
    04. Employee Department : Employee's current Department - Sales OR Human Resources OR Development OR Data Science OR Research & Development OR Finance
    
    05. Years of Experience In Current Role : Employee's no. of Years in the Existing Role
    
    06. Employee Job Role : Includes - Sales Executive,Manager,Developer,Sales Representative,Senior Developer R&D,Data Scientist,Finance Manager,Business Analyst,Technical Lead,Research Director,Delivery Manager
    
    07. Years With Current Manager: Number of years spent with the Existing Manager
    
    08. Distance From Home: How far does the Employee Stay ?
    
    09. Years of Experience At Existing Company: Experience in years spent in the Existing Company
    
    10. Number of Companies Worked: How many Companies has the employee worked at.</b>

    ---
    parameters:
      - name: file
        in: formData
        type: file
        required: true
      
    responses:
        200:
            description: The ABC, Berkeley human resources department currently conducts performance appraisals with a 4-level rating scale focused on whether or not employees meet company goals.<b>Overall performance ratings are given on a 4-point scale, observing employees with performances that are Excellent (4), Good  (3), Needs Improvement (2), and Unacceptable (1)</b>.
        
        
    """
    df_test=pd.read_excel(request.files.get("file"))
    print(df_test.head())
    prediction6=classifier4.predict(df_test)
    
    return str(list(prediction6))






if __name__=='__main__':
    app.run()

!pip install flask_ngrok

from flask_ngrok import run_with_ngrok
# ! pip install flask
# ! pip install flasgger
# ! pip install pickle